name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v2
      with:
        ruby-version: '2.7'

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('Gemfile.lock') }}

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get -yqq install libsqlite3-dev chromium-browser
        bundle install --jobs 4 --retry 3

    - name: Test
      run: bin/test test/**/*_test.rb
